default_platform(:ios)

platform :ios do
  lane :release do
    app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_PRIVATE_KEY'],
      is_key_content_base64: false
    )

    get_certificates
    get_provisioning_profile(
      app_identifier: "com.gyeningcorp.parkspot",
      readonly: false
    )

    build_app(
      scheme: "IForGotParking",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.gyeningcorp.parkspot" => "match AppStore com.gyeningcorp.parkspot"
        }
      }
    )

    upload_to_app_store(
      app_identifier: "com.gyeningcorp.parkspot",
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      force: true
    )
  end
end
