default_platform(:ios)

platform :ios do
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_filepath: ENV['ASC_KEY_FILEPATH'],
      duration: 1200,
      in_house: false
    )

    build_app(
      scheme: "IForGotParking",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "com.gyeningcorp.parkspot",
      skip_waiting_for_build_processing: true
    )
  end
end
